baseURL = ''
languageCode = 'en-us'
title = 'raw input'

theme = "hugo-theme-m10c"

[pagination]
  pagerSize = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = 3

[params]
  author = "gabriel"
  description = "homem cis hétero, 23 anos, 183cm, nerd"
  menu_item_separator = "|"
  avatar = "avatar.jpg"
  favicon = "favicon.ico"
  [[params.social]]
    icon = "brand-github"
    name = "Github"
    url = "https://github.com/cauzinnn"
  [[params.social]]
    icon = "brand-twitter"
    name = "Twitter"
    url = "https://twitter.com/_nobre___"

  # Default theme
  [params.style]
    darkestColor = "#2e3440"
    darkColor = "#2e3440"
    lightColor = "#2e3440"
    lightestColor = "#ffffff"
    primaryColor = "#81a1c1"

  # Green theme
  # [params.style]
  #   darkestColor = "#315659"
  #   darkColor = "#253031"
  #   lightColor = "#96a879"
  #   lightestColor = "#fff"
  #   primaryColor = "#dad865"

  # Red theme
  # [params.style]
  #   darkestColor = "#d35050"
  #   darkColor = "#212121"
  #   lightColor = "#d6d6d6"
  #   lightestColor = "#d3d3d3"
  #   primaryColor = "#ffffff"